### ISSUE TITLE
cannot open object clutter :(

### ISSUE THREAD

**Issue by Justfunnydude** [SMDDevs/SMD_Sahrani_A3#4]
Hi all, ive downloaded your fantastic map but when i open editore appear this message:
http://i.imgur.com/PECLSI4.jpg?1
Cannot open object
ca\plants2\clutter\c_strubble.p3d

Thx for any answer

**Comment by NonovUrbizniz** [comment]
Sorry, haven't been actively checking this at all. 

That is a CA object, so it would indicate that you don't have AiA running? or that that file is missing from your install of AiA.
